id: I04F98776
legacy_id: P004480
ocr_import_info:
  bdrc_scan_id: W3CN3103
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T04:50:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:17:47.418616+00:00'
last_modified: 2022-09-03 21:18:08.355856
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3103
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3103
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྟག་ལ་མེ་འབར་ཕྱི་ནང་གསང་གསུམ་གྱི་ལག་ལེན་གསལ་བ།
statistics:
  ocr_word_mean_confidence_index: 0.6023828102159988
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I3CN3109:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3109
      total_pages: 1003
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3109.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.6023828102159988
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
