id: I04F98776
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T04:56:25+00:00'
last_modified: '2022-06-08T01:23:09.950925+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3103
  title: སྟག་ལ་མེ་འབར་ཕྱི་ནང་གསང་གསུམ་གྱི་ལག་ལེན་གསལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D4EE:
      image_group_id: I3CN3109
      title: ''
      total_pages: 1003
      order: 1
      base_file: D4EE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
