id: P004480
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3103
  title: སྟག་ལ་མེ་འབར་ཕྱི་ནང་གསང་གསུམ་གྱི་ལག་ལེན་གསལ་བ།
  author: ''
  volumes:
    6a3a2f6d29054573a51650d5690e9b66:
      image_group_id: I3CN3109
      title: ''
      volume_number: 1
      total_pages: 1003
